#!/bin/bash
#The user running this script accepts all responsibility of the actions. The creator of the script cannot be held liable for any reason including the content.
echo "The user running this script accepts all responsibility of the actions. The creator of the script cannot be held liable for any reason including the content."
echo "----------------------------------------------------------------------------"
echo "Enter y to accept terms and start or n to end, press enter after selection"
read check

if [[ $check = "y" ]] 
        then
                echo "Starting FileWave removal, please wait..."
        elif [[ $check = "n" ]] 
                then 
                        echo "CANCELED"
                        exit 0
                else
                        echo "INVALID OPTION ENDING PROGRAM"
                        exit 0
fi
sleep 1
printf "\n"
sudo rm -rfv /usr/local/sbin/FileWave.app/
sudo rm -rfv /Library/Frameworks/FileWaveCore.framework/
sudo rm -rfv /Library/Application\ Support/FileWave/
sudo rm -rfv /private/var/FileWave/custom.ini
sudo rm -rfv /usr/local/munki/
sudo rm -rfv /usr/local/filewave/
sudo rm -rfv /Library/Applications/Managed\ Software\ Center.app/
sudo rm -rfv /Users/$USER/Library/Applications/FileWave\ Kiosk.app/
sudo rm -rfv /Library/Applications/FileWave\ Kiosk.app/
sudo rm -rfv /Users/$USER/Library/Applications/Managed\ Software\ Center.app/
sudo rm -rfv /private/var/db/receipts/com.filewave.fwcld.pkg.bom
sudo rm -rfv /private/var/db/receipts/com.filewave.fwcld.pkg.plist
sudo rm -rfv /private/var/db/receipts/com.filewave.fwxserver.mdm.pkg.bom
sudo rm -rfv /private/var/db/receipts/com.filewave.fwxserver.mdm.pkg.plist
sudo rm -rfv /private/var/db/receipts/com.filewave.fwxserver.pkg.bom
sudo rm -rfv /private/var/db/receipts/com.filewave.fwxserver.pkg.plist
sudo rm -rfv /Library/Preferences/com.filewave.fwxserver.plist
sudo rm -rfv /Library/LaunchAgents/com.filewave.fwGUI.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwcld.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwxserver-admin.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwxserver-apache.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwxserver-ldap.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwxserver-scheduler.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.fwxserver-server.plist
sudo rm -rfv /Library/LaunchDaemons/com.filewave.postgresql.plist
sudo rm -rfv /Library/Preferences/com.filewave.WinClient.plist
sudo rm -rfv /Applications/Managed\ Software\ Center.app
sudo rm -rfv /Library/LaunchDaemons/org.uaschools.removeUAsetupnetwork.plist
sudo rm -rfv /Library/LaunchDaemons/org.uaschools.studentadmin.plist
sudo rm -rfv /private/var/db/receipts/com.github.makeprofilepkg.UASchoolsWireless.bom
sudo rm -rfv /private/var/db/receipts/com.github.makeprofilepkg.UASchoolsWireless.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.ibossClient.iboss.register-1.pkg.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.ibossClient.iboss.register-1.pkg.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.ibossClient.iboss.register.pkg.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.ibossClient.iboss.register.pkg.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.adbindUA.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.adbindUA.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.removeUAsetup.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.removeUAsetup.plist
sudo rm -rfv /usr/local/share/UASchoolsWireless.mobileconfig
sudo rm -rfv /Library/Scripts/UAScripts
sudo rm -rfv "/Users/$USER/Library/Preferences/com.filewave-kiosk.FileWave Kiosk.plist"
sudo rm -rfv /Library/LaunchAgents/com.filewave.fwVNCServer.plist
sudo rm -rfv /Library/LaunchAgents/com.filewave.fwGUI.plist
sudo rm -rfv /Library/LaunchAgents/com.filewave.fwVNCServer.plist.bak
sudo rm -rfv /Library/FW_scripts
sudo rm -rfv "/usr/local/sbin/Client Assistant.app"
sudo rm -rfv /private/var/FileWave/
sudo rm -rfv /usr/local/etc/FileWaveInstallers/
sudo rm -rfv /usr/local/etc/FileWaveInstallerLogfiles/
sudo rm -rfv /Users/$USER/Library/Application\ Support/FileWave
sudo rm -rfv /private/var/FileWave/
sudo rm -rfv /Applications/FileWave\ Kiosk.app/
sudo rm -rfv /Library/LaunchDaemons/iboss.register.plist
sudo rm -rfv /private/var/root/Library/Preferences/com.filewave.client.FileWave\ Client.plist
sudo rm -rfv /Library/LaunchDaemons/org.uaschools.studentadmin.plist
sudo rm -rfv "/private/var/root/Library/Application Support/FileWave"
sudo chown $USER /private/var/FileWave/
sudo mv /private/var/FileWave/ noo
sudo rm -rfv noo
sudo rm -rf "/Library/Managed Preferences"
sudo launchctl unload /Library/LaunchAgents/com.filewave.fwVNCServer.plist
sudo launchctl unload /Library/LaunchAgents/com.filewave.fwGUI.plist
sudo launchctl unload /Library/LaunchAgents/com.filewave.fwVNCServer.plist.bak
echo "Removing hidden backdoor... yikes"
#NEW ADDITIONS 2017


sudo rm /usr/local/bin/fwcontrol
sudo rm /usr/local/bin/mobilefilter
sudo rm /usr/local/bin/useragent
sudo rm /Library/LaunchDaemons/com.lightspeedsystems.mobilefilter.plist
sudo rm /Library/LaunchDaemons/com.lightspeedsystems.useragent.plist
sudo rm /private/var/db/receipts/com.lightspeedsystems.mobilefilter.bom
sudo rm /private/var/db/receipts/com.lightspeedsystems.mobilefilter.plist
sudo rm /private/var/db/receipts/com.lightspeedsystems.useragent.bom
sudo rm /private/var/db/receipts/com.lightspeedsystems.useragent.plist
sudo rm -rf /private/var/db/ConfigurationProfiles/Store/
sudo rm /Library/lssys/mobilefilter.xml
sudo rm -rf /System/Library/Extensions/MobileFilterKext.kext

sudo rm -rfv /Library/LaunchDaemons/org.uaschools.RemoveGuestSSIDs.plist
sudo rm -rfv /Library/LaunchDaemons/org.uaschools.TestingCompliance.plist
sudo rm -rfv /Library/LaunchDaemons/org.uaschools.TestingCompliance2.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.AIRtestingSL.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.AIRtestingSL.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.chrome.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.chrome.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.firmwaresettings.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.firmwaresettings.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.mdmenrollment.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.mdmenrollment.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.munkiConfigMacPros.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.munkiConfigMacPros.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.ACTTESTING201617.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.ACTTESTING201617.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.AIRTESTING201617.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.pkg.AIRTESTING201617.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.time.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.time.plist
sudo rm -rfv /private/var/db/receipts/org.uaschools.ua_macbasics.bom
sudo rm -rfv /private/var/db/receipts/org.uaschools.ua_macbasics.plist
sudo rm -rfv /Scripts/UAScripts/receipts/org.uaschools.time
sudo rm -rfv /Library/Preferences/com.filewave.Client.plist
sudo rm -rfv /Library/Preferences/com.filewave.plist
sudo rm -rfv /private/var/FileWave

# END 2017
sleep 2
sudo dscl . -delete /Users/uaschools
sudo rm -rfv /Users/uaschools/
echo "We are now going to remove the Management profile, this will also remove your current network, you will need to sign in to another"
echo "Enter y"
sudo /usr/bin/profiles -D
snumber=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
sudo dsconfigad -force -remove -u $snumber -p $snumber
sudo pkill mobilefilter
adcheck=$(sudo dsconfigad -show)

if [[ $adcheck == "" ]] 
        then
                echo "AD has been unbound"
        else
                echo "."
                echo "ERROR: AD unbind attept 1 has failed"
                echo "Please enter your password, this will be in plain text"
                read passw
                sudo dsconfigad -force -remove -u $USER -p $passw
fi
adcheck2=$(sudo dsconfigad -show)
if [[ $adcheck2 == "" ]] ;
        then
                echo "AD has been unbound" 
        else
                echo "."
                echo "ERROR: AD unbind attept 2 has failed"
                echo "you must manually unbind"
                echo "To unbind the AD go to Sytem Preferenced, Users and groups, Login Options, Click edit on network account server"
                echo "Click on the AD with green indicator, remove it by clicking the minus, when it prompts for username and password"
                echo "enter $snumber as the username and password"
                echo "Hit enter to continue"
                read hey
fi

filewavePID="$(sudo ps aux | grep "[f]wGUI" | awk '{print $2}')"
if [[ $filewavePID == "" ]] ;
        then
                echo "fwGUI not running!"
                exit 0
        else
sudo kill -9 $filewavePID
fi
exit 0
